import type { Exercise, PracticeFocus } from '../types';
import { buildExerciseSignature, normalizeExerciseSignature } from '../utils/exerciseSignature';

type FallbackTemplate = Omit<Exercise, 'id' | 'userAnswer' | 'isCorrect'>;

const FALLBACK_TEMPLATES: FallbackTemplate[] = [
  {
    type: 'vocabulary_translation',
    category: 'vocabulary',
    title: 'Слова: переклад',
    instruction: 'Переклади слово з української на англійську одним словом.',
    question: 'подорож',
    correctAnswer: 'travel',
    topic: 'travel_vocabulary',
    answerFormat: 'text',
    explanation: 'Travel означає "подорож".',
  },
  {
    type: 'vocabulary_translation',
    category: 'vocabulary',
    title: 'Слова: переклад',
    instruction: 'Переклади слово з української на англійську одним словом.',
    question: 'сусід',
    correctAnswer: 'neighbor',
    topic: 'daily_vocabulary',
    answerFormat: 'text',
    explanation: 'Neighbor означає "сусід".',
  },
  {
    type: 'vocabulary_translation',
    category: 'vocabulary',
    title: 'Слова: переклад',
    instruction: 'Переклади слово з української на англійську одним словом.',
    question: 'магазин',
    correctAnswer: 'shop',
    topic: 'shopping_vocabulary',
    answerFormat: 'text',
    explanation: 'Shop означає "магазин".',
  },
  {
    type: 'vocabulary_translation',
    category: 'vocabulary',
    title: 'Слова: переклад',
    instruction: 'Переклади слово з української на англійську одним словом.',
    question: 'валіза',
    correctAnswer: 'suitcase',
    topic: 'travel_vocabulary',
    answerFormat: 'text',
    explanation: 'Suitcase означає "валіза".',
  },
  {
    type: 'vocabulary_translation',
    category: 'vocabulary',
    title: 'Слова: переклад',
    instruction: 'Переклади слово з української на англійську одним словом.',
    question: 'сніданок',
    correctAnswer: 'breakfast',
    topic: 'food_vocabulary',
    answerFormat: 'text',
    explanation: 'Breakfast означає ранковий прийом їжі, тобто "сніданок".',
  },
  {
    type: 'vocabulary_multiple_choice',
    category: 'vocabulary',
    title: 'Слова: вибір правильної відповіді',
    instruction: 'Обери правильний переклад англійського слова.',
    question: 'Що означає слово "borrow"?',
    correctAnswer: 'позичати',
    topic: 'daily_vocabulary',
    answerFormat: 'choice',
    choices: ['позичати', 'ламати', 'купувати', 'забувати'],
    explanation: 'Borrow означає взяти щось у когось на певний час.',
  },
  {
    type: 'vocabulary_multiple_choice',
    category: 'vocabulary',
    title: 'Слова: вибір правильної відповіді',
    instruction: 'Обери правильний переклад англійського слова.',
    question: 'Що означає слово "ticket"?',
    correctAnswer: 'квиток',
    topic: 'travel_vocabulary',
    answerFormat: 'choice',
    choices: ['кишеня', 'квиток', 'валіза', 'вікно'],
    explanation: 'Ticket означає квиток на транспорт, подію або вхід.',
  },
  {
    type: 'vocabulary_multiple_choice',
    category: 'vocabulary',
    title: 'Слова: вибір правильної відповіді',
    instruction: 'Обери правильний переклад англійського слова.',
    question: 'Що означає слово "cheap"?',
    correctAnswer: 'дешевий',
    topic: 'shopping_vocabulary',
    answerFormat: 'choice',
    choices: ['гарячий', 'дешевий', 'вузький', 'швидкий'],
    explanation: 'Cheap означає недорогий або дешевий.',
  },
  {
    type: 'vocabulary_multiple_choice',
    category: 'vocabulary',
    title: 'Слова: вибір правильної відповіді',
    instruction: 'Обери правильний переклад англійського слова.',
    question: 'Що означає слово "stairs"?',
    correctAnswer: 'сходи',
    topic: 'daily_vocabulary',
    answerFormat: 'choice',
    choices: ['вікно', 'сходи', 'тарілка', 'вулиця'],
    explanation: 'Stairs означає сходи між поверхами.',
  },
  {
    type: 'vocabulary_multiple_choice',
    category: 'vocabulary',
    title: 'Слова: вибір правильної відповіді',
    instruction: 'Обери правильний переклад англійського слова.',
    question: 'Що означає слово "receipt"?',
    correctAnswer: 'чек',
    topic: 'shopping_vocabulary',
    answerFormat: 'choice',
    choices: ['пакет', 'ціна', 'чек', 'каса'],
    explanation: 'Receipt це чек, який ти отримуєш після покупки.',
  },
  {
    type: 'grammar_fill_blank',
    category: 'grammar',
    title: 'Граматика: встав слово',
    instruction: 'Встав правильне слово англійською у пропуск.',
    question: 'She _ to the gym every Monday.',
    correctAnswer: 'goes',
    topic: 'present_simple',
    answerFormat: 'text',
    explanation: 'Потрібно goes, бо з she у Present Simple додаємо -es.',
  },
  {
    type: 'grammar_fill_blank',
    category: 'grammar',
    title: 'Граматика: встав слово',
    instruction: 'Встав правильне слово англійською у пропуск.',
    question: 'I have lived here _ 2020.',
    correctAnswer: 'since',
    topic: 'prepositions',
    answerFormat: 'text',
    explanation: 'Since вживаємо з конкретною точкою початку в часі.',
  },
  {
    type: 'grammar_fill_blank',
    category: 'grammar',
    title: 'Граматика: встав слово',
    instruction: 'Встав правильне слово англійською у пропуск.',
    question: 'If I _ more time, I would learn Spanish too.',
    correctAnswer: 'had',
    topic: 'conditionals',
    answerFormat: 'text',
    explanation: 'У second conditional в if-частині йде Past Simple.',
  },
  {
    type: 'grammar_fill_blank',
    category: 'grammar',
    title: 'Граматика: встав слово',
    instruction: 'Встав правильне слово англійською у пропуск.',
    question: 'There is _ apple on the table.',
    correctAnswer: 'an',
    topic: 'articles',
    answerFormat: 'text',
    explanation: 'Перед словом, що починається на vowel sound, вживаємо an.',
  },
  {
    type: 'grammar_fill_blank',
    category: 'grammar',
    title: 'Граматика: встав слово',
    instruction: 'Встав правильне слово англійською у пропуск.',
    question: 'They _ playing football when it started to rain.',
    correctAnswer: 'were',
    topic: 'past_continuous',
    answerFormat: 'text',
    explanation: 'З they у Past Continuous вживаємо were.',
  },
  {
    type: 'grammar_multiple_choice',
    category: 'grammar',
    title: 'Граматика: обери варіант',
    instruction: 'Обери правильну граматичну форму.',
    question: 'By the time we arrived, the film _ already started.',
    correctAnswer: 'had',
    topic: 'past_perfect',
    answerFormat: 'choice',
    choices: ['has', 'had', 'have', 'was'],
    explanation: 'Past Perfect будується з had + past participle.',
  },
  {
    type: 'grammar_multiple_choice',
    category: 'grammar',
    title: 'Граматика: обери варіант',
    instruction: 'Обери правильний артикль.',
    question: 'He bought _ umbrella because it was raining.',
    correctAnswer: 'an',
    topic: 'articles',
    answerFormat: 'choice',
    choices: ['a', 'an', 'the', 'no article'],
    explanation: 'Перед vowel sound треба вживати an.',
  },
  {
    type: 'grammar_multiple_choice',
    category: 'grammar',
    title: 'Граматика: обери варіант',
    instruction: 'Обери правильну форму дієслова.',
    question: 'How long _ you been studying English?',
    correctAnswer: 'have',
    topic: 'present_perfect',
    answerFormat: 'choice',
    choices: ['have', 'has', 'did', 'are'],
    explanation: 'З you у Present Perfect вживаємо have.',
  },
  {
    type: 'grammar_multiple_choice',
    category: 'grammar',
    title: 'Граматика: обери варіант',
    instruction: 'Обери правильний прийменник.',
    question: 'She is interested _ modern art.',
    correctAnswer: 'in',
    topic: 'prepositions',
    answerFormat: 'choice',
    choices: ['in', 'on', 'at', 'for'],
    explanation: 'Стійкий вираз: interested in.',
  },
  {
    type: 'grammar_multiple_choice',
    category: 'grammar',
    title: 'Граматика: обери варіант',
    instruction: 'Обери правильну форму дієслова.',
    question: 'If he studies more, he _ pass the exam.',
    correctAnswer: 'will',
    topic: 'conditionals',
    answerFormat: 'choice',
    choices: ['will', 'would', 'did', 'has'],
    explanation: 'У first conditional після if-частини в основній частині часто йде will.',
  },
  {
    type: 'speaking_text',
    category: 'speaking',
    title: 'Speaking: письмова практика',
    instruction: 'Напиши 1-2 короткі речення англійською на цю тему.',
    question: 'Розкажи англійською, що ти зазвичай робиш зранку.',
    correctAnswer: 'I usually wake up early, make breakfast, and start my day with tea.',
    sampleAnswer: 'I usually wake up early, make breakfast, and start my day with tea.',
    topic: 'daily_routine_speaking',
    answerFormat: 'long_text',
    explanation: 'Головне: повна думка англійською і базово правильний порядок слів.',
  },
  {
    type: 'speaking_text',
    category: 'speaking',
    title: 'Speaking: письмова практика',
    instruction: 'Напиши 1-2 короткі речення англійською на цю тему.',
    question: 'Опиши англійською свою улюблену їжу.',
    correctAnswer: 'My favorite food is pasta because it is tasty and easy to cook.',
    sampleAnswer: 'My favorite food is pasta because it is tasty and easy to cook.',
    topic: 'food_speaking',
    answerFormat: 'long_text',
    explanation: 'Важливо назвати їжу і коротко пояснити why.',
  },
  {
    type: 'speaking_text',
    category: 'speaking',
    title: 'Speaking: письмова практика',
    instruction: 'Напиши 1-2 короткі речення англійською на цю тему.',
    question: 'Розкажи англійською, куди ти хочеш поїхати у відпустку.',
    correctAnswer: 'I want to travel to Italy because I love the food and the architecture.',
    sampleAnswer: 'I want to travel to Italy because I love the food and the architecture.',
    topic: 'travel_speaking',
    answerFormat: 'long_text',
    explanation: 'Скажи, куди хочеш поїхати, і назви причину.',
  },
  {
    type: 'speaking_text',
    category: 'speaking',
    title: 'Speaking: письмова практика',
    instruction: 'Напиши 1-2 короткі речення англійською на цю тему.',
    question: 'Опиши англійською свою кімнату або робоче місце.',
    correctAnswer: 'My room is bright and tidy, and I study at a small desk near the window.',
    sampleAnswer: 'My room is bright and tidy, and I study at a small desk near the window.',
    topic: 'daily_routine_speaking',
    answerFormat: 'long_text',
    explanation: 'Добре назвати 1-2 деталі і місце, де ти щось робиш.',
  },
  {
    type: 'speaking_text',
    category: 'speaking',
    title: 'Speaking: письмова практика',
    instruction: 'Напиши 1-2 короткі речення англійською на цю тему.',
    question: 'Розкажи англійською, що ти любиш робити у вихідні.',
    correctAnswer: 'On weekends I like to walk with friends and watch a good film in the evening.',
    sampleAnswer: 'On weekends I like to walk with friends and watch a good film in the evening.',
    topic: 'future_plans',
    answerFormat: 'long_text',
    explanation: 'Скажи, що саме любиш робити і коли це зазвичай відбувається.',
  },
  {
    type: 'listening_dictation',
    category: 'listening',
    title: 'Слух: диктант',
    instruction: 'Прослухай фразу і впиши її англійською якомога точніше.',
    question: 'I usually take the bus to work in the morning.',
    correctAnswer: 'I usually take the bus to work in the morning.',
    topic: 'daily_vocabulary',
    answerFormat: 'text',
    explanation: 'Потрібно відтворити всю почуту фразу без пропусків.',
  },
  {
    type: 'listening_dictation',
    category: 'listening',
    title: 'Слух: диктант',
    instruction: 'Прослухай фразу і впиши її англійською якомога точніше.',
    question: 'My brother cooks dinner every Friday evening.',
    correctAnswer: 'My brother cooks dinner every Friday evening.',
    topic: 'food_vocabulary',
    answerFormat: 'text',
    explanation: 'Слухай уважно весь порядок слів і не пропусти часовий вираз.',
  },
  {
    type: 'listening_dictation',
    category: 'listening',
    title: 'Слух: диктант',
    instruction: 'Прослухай фразу і впиши її англійською якомога точніше.',
    question: 'They are waiting for the train at platform three.',
    correctAnswer: 'They are waiting for the train at platform three.',
    topic: 'travel_vocabulary',
    answerFormat: 'text',
    explanation: 'Тут важливо точно почути дієслово, артикль і місце.',
  },
  {
    type: 'listening_choice',
    category: 'listening',
    title: 'Слух: знайди слово',
    instruction: 'Прослухай фразу і обери слово, яке справді звучало в ній.',
    question: 'We need to book a hotel near the station.',
    correctAnswer: 'hotel',
    topic: 'travel_vocabulary',
    answerFormat: 'choice',
    choices: ['hotel', 'airport', 'window', 'kitchen'],
    explanation: 'У цій вправі треба вибрати слово, яке реально звучить у фразі.',
  },
  {
    type: 'listening_choice',
    category: 'listening',
    title: 'Слух: знайди слово',
    instruction: 'Прослухай фразу і обери слово, яке справді звучало в ній.',
    question: 'Please put the apples on the kitchen table.',
    correctAnswer: 'apples',
    topic: 'food_vocabulary',
    answerFormat: 'choice',
    choices: ['apples', 'garden', 'taxi', 'lamp'],
    explanation: 'Треба вибрати саме слово, яке реально звучить усередині фрази.',
  },
  {
    type: 'listening_choice',
    category: 'listening',
    title: 'Слух: знайди слово',
    instruction: 'Прослухай фразу і обери слово, яке справді звучало в ній.',
    question: 'Our teacher opened the window before the lesson started.',
    correctAnswer: 'window',
    topic: 'daily_vocabulary',
    answerFormat: 'choice',
    choices: ['window', 'backpack', 'market', 'banana'],
    explanation: 'Сфокусуйся на одному слові, яке реально прозвучало в реченні.',
  },
  {
    type: 'listening_dictation',
    category: 'listening',
    title: 'Слух: диктант',
    instruction: 'Прослухай фразу і впиши її англійською якомога точніше.',
    question: 'She always checks her email before lunch.',
    correctAnswer: 'She always checks her email before lunch.',
    topic: 'work_vocabulary',
    answerFormat: 'text',
    explanation: 'Зверни увагу на закінчення дієслова і порядок слів у фразі.',
  },
  {
    type: 'listening_dictation',
    category: 'listening',
    title: 'Слух: диктант',
    instruction: 'Прослухай фразу і впиши її англійською якомога точніше.',
    question: 'We bought fresh bread at the market this morning.',
    correctAnswer: 'We bought fresh bread at the market this morning.',
    topic: 'shopping_vocabulary',
    answerFormat: 'text',
    explanation: 'Тут важливо точно почути форму дієслова в минулому часі.',
  },
  {
    type: 'listening_choice',
    category: 'listening',
    title: 'Слух: знайди слово',
    instruction: 'Прослухай фразу і обери слово, яке справді звучало в ній.',
    question: 'The doctor asked me to drink more water every day.',
    correctAnswer: 'water',
    topic: 'daily_vocabulary',
    answerFormat: 'choice',
    choices: ['water', 'forest', 'camera', 'pencil'],
    explanation: 'Потрібно почути і впіймати слово, яке реально прозвучало у фразі.',
  },
  {
    type: 'listening_choice',
    category: 'listening',
    title: 'Слух: знайди слово',
    instruction: 'Прослухай фразу і обери слово, яке справді звучало в ній.',
    question: 'Their children played outside near the garden gate.',
    correctAnswer: 'garden',
    topic: 'nature_vocabulary',
    answerFormat: 'choice',
    choices: ['garden', 'office', 'mirror', 'airport'],
    explanation: 'Серед варіантів треба вибрати саме слово, яке є в реченні.',
  },
  {
    type: 'reading_comprehension',
    category: 'reading',
    title: 'Читання: розуміння',
    instruction: 'Прочитай текст і дай коротку відповідь англійською за його змістом.',
    passage:
      'Anna works in a cafe near her home. She starts at eight in the morning and finishes at three in the afternoon. After work, she often buys fruit and walks to the park.',
    question: 'Where does Anna work?',
    correctAnswer: 'She works in a cafe near her home.',
    topic: 'daily_life_reading',
    answerFormat: 'text',
    explanation: 'Відповідь є в першому реченні тексту.',
  },
  {
    type: 'reading_comprehension',
    category: 'reading',
    title: 'Читання: розуміння',
    instruction: 'Прочитай текст і дай коротку відповідь англійською за його змістом.',
    passage:
      'Mark loves quiet places. Every Saturday morning he goes to the town library with his sister. They read for an hour, choose two books, and then drink hot chocolate in a small cafe nearby.',
    question: 'When does Mark go to the library?',
    correctAnswer: 'He goes to the library every Saturday morning.',
    topic: 'work_reading',
    answerFormat: 'text',
    explanation: 'Потрібно знайти часову підказку в другому реченні.',
  },
  {
    type: 'reading_comprehension',
    category: 'reading',
    title: 'Читання: розуміння',
    instruction: 'Прочитай текст і дай коротку відповідь англійською за його змістом.',
    passage:
      'Emma is on holiday in the mountains. She wakes up early, takes photos of the lake, and writes short notes in her travel journal. In the evening, she calls her family from the hotel balcony.',
    question: 'What does Emma write in?',
    correctAnswer: 'She writes in her travel journal.',
    topic: 'travel_reading',
    answerFormat: 'text',
    explanation: 'Відповідь захована в середині тексту, де описано її ранкові дії.',
  },
  {
    type: 'reading_comprehension',
    category: 'reading',
    title: 'Читання: розуміння',
    instruction: 'Прочитай текст і дай коротку відповідь англійською за його змістом.',
    passage:
      'Leo works from home on weekdays. He usually starts at nine o clock, answers client messages, and joins two online meetings before lunch. After work, he goes cycling in the park if the weather is good.',
    question: 'What does Leo do before lunch?',
    correctAnswer: 'He answers client messages and joins two online meetings before lunch.',
    topic: 'work_reading',
    answerFormat: 'text',
    explanation: 'Відповідь треба зібрати з середини тексту, де описано його робочий ранок.',
  },
  {
    type: 'reading_comprehension',
    category: 'reading',
    title: 'Читання: розуміння',
    instruction: 'Прочитай текст і дай коротку відповідь англійською за його змістом.',
    passage:
      'Sofia is preparing for a family dinner tonight. She cleaned the kitchen in the afternoon, bought vegetables and juice, and put a cake in the fridge. Her parents will arrive at seven o clock.',
    question: 'What did Sofia put in the fridge?',
    correctAnswer: 'She put a cake in the fridge.',
    topic: 'daily_life_reading',
    answerFormat: 'text',
    explanation: 'Потрібно знайти конкретну дію в другій половині тексту.',
  },
  {
    type: 'speaking_voice',
    category: 'speaking',
    title: 'Speaking: голосова практика',
    instruction:
      'Скажи це речення вголос 2 рази, а потім впиши його сюди так, як ти його вимовив(ла).',
    question: 'Прочитай уголос: "I have been learning English for two years."',
    correctAnswer: 'I have been learning English for two years.',
    sampleAnswer: 'I have been learning English for two years.',
    topic: 'speaking_pronunciation',
    answerFormat: 'text',
    explanation:
      'Це вправа на впевненість і вимову. Після проговорювання важливо правильно відтворити фразу.',
  },
  {
    type: 'speaking_voice',
    category: 'speaking',
    title: 'Speaking: голосова практика',
    instruction:
      'Прочитай фразу вголос 2 рази, а потім впиши її так, як ти її вимовив(ла).',
    question: 'Прочитай уголос: "My favorite season is spring because everything becomes green."',
    correctAnswer: 'My favorite season is spring because everything becomes green.',
    sampleAnswer: 'My favorite season is spring because everything becomes green.',
    topic: 'speaking_pronunciation',
    answerFormat: 'text',
    explanation: 'Тут тренується плавність мовлення і відтворення довшого речення.',
  },
  {
    type: 'speaking_voice',
    category: 'speaking',
    title: 'Speaking: голосова практика',
    instruction:
      'Скажи речення вголос, зверни увагу на вимову, а потім впиши його сюди.',
    question: 'Прочитай уголос: "I usually drink coffee before I start working."',
    correctAnswer: 'I usually drink coffee before I start working.',
    sampleAnswer: 'I usually drink coffee before I start working.',
    topic: 'daily_routine_speaking',
    answerFormat: 'text',
    explanation: 'Ця вправа допомагає закріпити ритм простого повсякденного речення.',
  },
  {
    type: 'speaking_voice',
    category: 'speaking',
    title: 'Speaking: голосова практика',
    instruction:
      'Прочитай фразу вголос кілька разів, а потім впиши її так, як ти її вимовив(ла).',
    question: 'Прочитай уголос: "We are meeting our friends at the cinema tonight."',
    correctAnswer: 'We are meeting our friends at the cinema tonight.',
    sampleAnswer: 'We are meeting our friends at the cinema tonight.',
    topic: 'travel_speaking',
    answerFormat: 'text',
    explanation: 'Тут тренується чітка вимова знайомих слів у природному темпі.',
  },
  {
    type: 'speaking_voice',
    category: 'speaking',
    title: 'Speaking: голосова практика',
    instruction:
      'Скажи це речення вголос, а потім впиши його сюди якомога точніше.',
    question: 'Прочитай уголос: "The weather is warmer today, so I opened the window."',
    correctAnswer: 'The weather is warmer today, so I opened the window.',
    sampleAnswer: 'The weather is warmer today, so I opened the window.',
    topic: 'speaking_pronunciation',
    answerFormat: 'text',
    explanation: 'Вправа допомагає тримати ритм довшого речення і не губити закінчення слів.',
  },
];

function filterTemplatesByFocus(focus: PracticeFocus) {
  if (focus === 'mixed') {
    return FALLBACK_TEMPLATES;
  }

  return FALLBACK_TEMPLATES.filter((template) => template.category === focus);
}

export function getFallbackTemplates(focus: PracticeFocus = 'mixed'): FallbackTemplate[] {
  return filterTemplatesByFocus(focus).map((template) => ({
    ...template,
    choices: template.choices ? [...template.choices] : undefined,
  }));
}

export function buildFallbackExercise(
  preferredTopic?: string,
  focus: PracticeFocus = 'mixed',
  recentSignatures: string[] = []
): Exercise {
  const normalizedTopic = preferredTopic?.trim().toLowerCase();
  const focusTemplates = filterTemplatesByFocus(focus);
  const matchingTemplates = normalizedTopic
    ? focusTemplates.filter((template) => template.topic === normalizedTopic)
    : focusTemplates;
  const source = matchingTemplates.length > 0 ? matchingTemplates : focusTemplates;
  const recentSet = new Set(recentSignatures.map(normalizeExerciseSignature));
  const uniquePool = source.filter(
    (template) => !recentSet.has(buildExerciseSignature(template))
  );
  const finalPool = uniquePool.length > 0 ? uniquePool : source;
  const selectedTemplate = finalPool[Math.floor(Math.random() * finalPool.length)];

  return {
    ...selectedTemplate,
    id: `fallback-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    userAnswer: '',
    isCorrect: false,
    explanation: `${selectedTemplate.explanation} Це локальна офлайн-вправа.`,
  };
}
